fix(core): install => git checkout tag method

diff --git a/core/core b/core/core
--- a/core/core
+++ b/core/core
@@ -204,7 +204,26 @@ zpackage::clone() {
     fi
   else
     cd $package_path
-    git pull origin master >> $ZMICRO_LOG_UPDATE_PATH 2>>$ZMICRO_LOG_ERROR_PATH
+    local current_tag=$(git describe --tags)
+    if [ "$current_tag" != "$version" ] && [ "$version" != "master" ]; then
+      # git fetch origin $version >> $ZMICRO_LOG_UPDATE_PATH 2>>$ZMICRO_LOG_ERROR_PATH
+      git fetch origin >> $ZMICRO_LOG_UPDATE_PATH 2>>$ZMICRO_LOG_ERROR_PATH
+      if [ "$?" != "0" ]; then
+        echo "[$(timestamp)][zpackage::clone] git fetch error ${name} ..."
+        tail -n 50 $ZMICRO_LOG_ERROR_PATH
+        exit -1
+      fi
+
+      local tag=$version
+      git checkout -b $version $tag >> $ZMICRO_LOG_UPDATE_PATH 2>>$ZMICRO_LOG_ERROR_PATH
+      if [ "$?" != "0" ]; then
+        echo "[$(timestamp)][zpackage::clone] git checkout error ${name} ..."
+        tail -n 50 $ZMICRO_LOG_ERROR_PATH
+        exit -1
+      fi
+    fi
+
+    git pull origin $version >> $ZMICRO_LOG_UPDATE_PATH 2>>$ZMICRO_LOG_ERROR_PATH
     if [ "$?" != "0" ]; then
       echo "[$(timestamp)][zpackage::clone] update package repo ${name} ..."
       tail -n 50 $ZMICRO_LOG_ERROR_PATH
